// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNlUocieFRVAvNFfB1HTOiiG0968c4Mfw',
    appId: '1:253361639643:web:bebf568044a86d1e693cfe',
    messagingSenderId: '253361639643',
    projectId: 'assistant-61bc8',
    authDomain: 'assistant-61bc8.firebaseapp.com',
    storageBucket: 'assistant-61bc8.appspot.com',
    measurementId: 'G-FR7718HY3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc6kRpThyLhokRSYEgT-htdOiO_NOzx_A',
    appId: '1:253361639643:android:bf92f1941dacbabd693cfe',
    messagingSenderId: '253361639643',
    projectId: 'assistant-61bc8',
    storageBucket: 'assistant-61bc8.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNlUocieFRVAvNFfB1HTOiiG0968c4Mfw',
    appId: '1:253361639643:web:513bea2f2b5cb64b693cfe',
    messagingSenderId: '253361639643',
    projectId: 'assistant-61bc8',
    authDomain: 'assistant-61bc8.firebaseapp.com',
    storageBucket: 'assistant-61bc8.appspot.com',
    measurementId: 'G-3PC69T15K2',
  );

}